apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-argo-events-helm
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    automated:
      prune: true
      selfHeal: true
      
  source:
    chart: argo-events
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.4.6

    # https://github.com/argoproj/argo-helm/tree/main/charts/argo-enents
    helm:
      valuesObject:
        fullnameOverride: argo-events

        crdAnnotations:
          argocd.argoproj.io/sync-wave: "-1"
        
        ## Controller ##
        controller:
          replicas: 1
          # resources:
          #   limits:
          #     cpu: 100m
          #     memory: 128Mi
          #   requests:
          #     cpu: 100m
          #     memory: 128Mi
          
          ## Monitoring ##
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              namespace: argo-events
              additionalLabels:
                prometheus.io/scrap-with: kube-prometheus-stack

          #pdb:
          #  enabled: true
          #  minAvailable: 1

        ## webhook ##
        


  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-events